title: Low%
version: 2.0
route:
  use: ./main.yaml

config:
- use: Pistonight/celer-presets/botw/map.yaml
- plugins:
  - use: link
- tags:
    blss:
      color: "#4bb"
    wb:
      color: "#9ff"
    dialog:
      color: "#c86"
    item:
      color: "#fc3"
    enemy:
      color: "#f43"
    milestone:
      color: "#3af"
    quest:
      includes: milestone
      italic: true
    npc:
      color: "#ffa"
    bold:
      bold: true
    loc:
      color: "#2e4"
    glitch:
      color: "#f3c"
    quote:
      italic: true
      color: "#eee"
    tab:
      includes: quote
      color: white
    s:
      strikethrough: true
- icons:
    shrine: https://icons.pistonite.org/icon/shrine.shrine.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
    tm: https://icons.pistonite.org/icon/location.travel_medallion.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
